resolver: lts-7.13
compiler: ghcjs-0.2.1.9007013_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007013_ghc-8.0.1:
           url:  http://ghcjs.tolysz.org/ghc-8.0-2016-12-18-lts-7.13-9007013.tar.gz
           sha1: 530c4ee5e19e2874e128431c7ad421e336df0303

extra-deps:
- reflex-0.5.0
- reflex-dom-0.4
- ghcjs-dom-0.2.4.0
- ref-tf-0.4.0.1
