resolver: lts-7.15
compiler: ghcjs-0.2.1.9007015_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007015_ghc-8.0.1:
           url:  http://ghcjs.tolysz.org/ghc-8.0-2017-01-11-lts-7.15-9007015.tar.gz
           sha1: 30d34e9d704bdb799066387dfa1ba98b8884d932

extra-deps:
- font-awesome-type-0.1
- reflex-0.5.0
- reflex-dom-0.4
- reflex-dom-contrib-0.5
- ghcjs-dom-0.2.4.0
- ref-tf-0.4.0.1
- prim-uniq-0.1.0.1
- zenc-0.1.1

packages:
- location: .
- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: 46304b448b4646b0d74e7b17c69a6d4ce21e5d25
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom.git
    commit: 773de9be7749b6a5bb55966d1a2632782d9bcde7
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom-contrib
    commit: 3a0a9bb3eeea330f6c20756dec09a43410395218
  extra-dep: true
